# Generated by Django 4.2.25 on 2025-10-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('number3', models.IntegerField()),
                ('number4', models.IntegerField()),
                ('is_cleared', models.BooleanField()),
                ('reset_count', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField()),
            ],
        ),
    ]
