# Generated by Django 4.2.25 on 2025-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ten_puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reset_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('number1', 'number2', 'number3', 'number4')},
        ),
        migrations.AlterModelTable(
            name='problem',
            table='problems',
        ),
    ]
